import type { Metadata } from "next";
import "./globals.css";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import NextTopLoader from "nextjs-toploader";
import { routing } from "@/i18n/routing";
import { Header } from "@/widgets/Header";
import { Footer } from "@/widgets/Footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
	params: Promise<{
		locale: string;
	}>;
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
	const { locale } = await params;
	if (!routing.locales.includes(locale as "ru" | "uz")) {
		notFound();
	}
	const messages = await getMessages();
	return (
		<html lang="en">
			<body>
				<NextTopLoader
					color="#ffffff"
					initialPosition={0.08}
					crawlSpeed={200}
					height={2}
					showSpinner={false}
					shadow="0 0 10px #fff,0 0 5px #fff"
				/>
				<div className="wrapper">
					<NextIntlClientProvider messages={messages}>
						<Header />
						{children}
						<Footer />
					</NextIntlClientProvider>
				</div>
			</body>
		</html>
	);
}
