import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import NextTopLoader from "nextjs-toploader";
import { routing } from "@/i18n/routing";
import { Header } from "@/widgets/Header";
import { Footer } from "@/widgets/Footer";
import UserContextProvider from "@/entities/user/model/UserContext";
import { cookies } from "next/headers";
import { authServerApi } from "@/features/auth/api/auth.server";
const inter = Inter({ subsets: ["latin"] });
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
	const cookieStore = await cookies();
	const accessToken = cookieStore.get("accessToken");
	const user = await authServerApi.getUser(accessToken?.value);
	const { locale } = await params;
	if (!routing.locales.includes(locale as "ru" | "uz")) {
		notFound();
	}
	const messages = await getMessages();
	return (
		<html lang="en">
			<body className={inter.className}>
				<ToastContainer position="top-right" autoClose={3000} hideProgressBar={true} newestOnTop={true} />
				<NextTopLoader
					color="#ffffff"
					initialPosition={0.08}
					crawlSpeed={200}
					height={2}
					showSpinner={false}
					shadow="0 0 10px #fff,0 0 5px #fff"
				/>
				<div className="wrapper">
					<NextIntlClientProvider messages={messages}>
						<UserContextProvider initialMe={user}>
							<Header />
							<main>{children}</main>
							<Footer />
						</UserContextProvider>
					</NextIntlClientProvider>
				</div>
			</body>
		</html>
	);
}
